### ISSUE TITLE
Move /tree to /lab?

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery-extensions#9] opened 2020-08-14 11:54 UTC
Hi, not really sure what I'm asking. So the NBGallery extension only activates when you navigate to /tree eh? Then it does all the magic to connect to nbgallery.. Is there a way to change that to be done when you go to /lab? Most/all our users use the /lab part of jupyterhub, and not so much the tree. It'd be nice to configure that..

**Comment by jeffyjefflabs** [comment] 2020-08-15 04:10
Yeah, that's on our radar - this is basically a duplicate of #5 although my comment there is a little out of date.  Lab has a completely new extension system from what's in the Classic UI (tree + notebook), so all the extensions have to be rewritten to work in Lab.  Also the next major version of Lab (3.0, targeted for release in the next couple months) is reworking extensions yet again - not sure how much it will change for the average extension author, but we haven't really started looking at it.  New development on the Classic UI has basically stopped, with Lab being the future, so we do need to start working on this soon.

**Comment by jeffyjefflabs** [comment] 2020-10-29 16:44
I'm going to close this - work on nbgallery extensions for JupyterLab is happening in a new repo - https://github.com/nbgallery/lab-extensions

**Closed as completed by jeffyjefflabs** 2020-10-29 16:44 UTC

**Comment by mcrutch** [comment] 2020-10-29 16:48
Just to add to this, the extension for environment registration and auto download are both finished for lab and available in version 0.1.0 of the jupyterlab-nbgallery python package (released today).

`pip install jupyterlab-nbgallery`
`jupyter lab build`
